export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const TOKEN = 'token'
export const USERINFO = 'userInfo'

export const AT_TIME = 'at_time'
export const AT_TIME_REFRESH = 'at_time_refresh'
export const AT_HOT = 'at_hot'
export const AT_HOT_REFRESH = 'at_hot_refresh'

export const MY_POST = 'my_post'
export const MY_POST_REFRESH = 'my_post_refresh'
export const MY_DONATE = 'my_donate'
export const MY_DONATE_REFRESH = 'my_donate_refresh'
export const MY_COMMENT = 'my_comment'
export const MY_COMMENT_REFRESH = 'my_comment_refresh'

export const MY_CIRCLE = 'my_circle'
export const MY_CIRCLE_REFRESH = 'my_circle_refresh'
export const ALL_CIRCLE = 'all_circle'
export const ALL_CIRCLE_REFRESH = 'all_circle_refresh'

export const INIT_TRON = 'init_tron'
export const CHECK_USER = 'check_user'
export const WRITE_HASH = 'write_hash'
export const SET_USER = 'set_user'
export const SET_CREATE_FEE = 'set_create_fee'

export const HOME_TIMELINE = 'home_timeline'
export const PUBLIC_TIMELINE = 'public_timeline'
export const MY_CONTENT = 'my_content'
export const HOME_REFRESH = 'home_refresh'
export const PUBLIC_REFRESH = 'public_refresh'
export const PROFILE_REFRESH = 'profile_refresh'
export const IMAGE_ZOOM = 'image_zoom'
export const DETAILCONTENT = 'detail_content'
export const CONTENT_COMMENTS = 'content_comments'
export const CONTENT_COMMENTS_REFRESH = 'content_comments_refresh'

export const AT_ME_STATUS = 'at_me_status'
export const AT_ME_STATUS_REFRESH = 'at_me_status_refresh'
export const AT_ME_COMMENT = 'at_me_comment'
export const AT_ME_COMMENT_REFRESH = 'at_me_comment_refresh'
export const RECEIVE_COMMENT = 'receive_comment'
export const RECEIVE_COMMENT_REFRESH = 'receive_comment_refresh'
export const SEND_COMMENT = 'send_comment'
export const SEND_COMMENT_REFRESH = 'send_comment_refresh'
export const MY_FOLLOWER = 'my_follower'
export const MY_FOLLOWER_REFRESH = 'my_follower_refresh'
export const MY_FRIEND = 'my_friend'
export const MY_FRIEND_REFRESH = 'my_friend_refresh'

